#!/usr/bin/python
import os
virtenv = os.environ['APPDIR'] + '/virtenv/'

pyver = os.environ['OPENSHIFT_PYTHON_VERSION']
pyver or pyver = '2.7'

#os.environ['PYTHON_EGG_CACHE'] = os.path.join(virtenv, 'lib/python2.7/site-packages')
os.environ['PYTHON_EGG_CACHE'] = os.path.join(virtenv, 'lib', 'python' + pyver, 'site-packages')
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')
try:
    execfile(virtualenv, dict(__file__=virtualenv))
except IOError:
    pass
from run import app as application
