#!/usr/bin/python
import os

virtenv_dir = os.path.join(os.environ['OPENSHIFT_PYTHON_DIR'], 'virtenv')
virtualenv  = os.path.join(virtenv_dir, 'bin', 'activate_this.py')

os.environ['PYTHON_EGG_CACHE'] = os.path.join(virtenv_dir, 'lib', \
	'python' + os.environ['OPENSHIFT_PYTHON_VERSION'], 'site-packages')

try:
    execfile(virtualenv, dict(__file__=virtualenv))
except IOError:
    pass
#
# IMPORTANT: Put any additional includes below this line.  If placed above this
# line, it's possible required libraries won't be in your searchable path
# 

from todoapp import app as application
from todoapp import *
db.create_all()
